"""initial universe from alembic

Revision ID: 380595206d34
Revises: 
Create Date: 2025-05-28 22:35:29.833165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380595206d34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_period',
    sa.Column('id_period', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=45), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_period'),
    schema='u'
    )
    op.create_table('faculty',
    sa.Column('id_faculty', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_faculty'),
    schema='u'
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipe_document', sa.String(length=100), nullable=True),
    sa.Column('number_document', sa.String(length=45), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('adress', sa.String(length=45), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('date_registration', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    schema='u'
    )
    op.create_table('program',
    sa.Column('id_program', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('semester_duration', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_faculty'], ['u.faculty.id_faculty'], ),
    sa.PrimaryKeyConstraint('id_program'),
    schema='u'
    )
    op.create_table('student',
    sa.Column('id_student', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('code_student', sa.String(length=45), nullable=True),
    sa.Column('current_semester', sa.Integer(), nullable=True),
    sa.Column('academinc_program', sa.String(length=45), nullable=True),
    sa.Column('date_of_entry', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['u.user.id_user'], ),
    sa.PrimaryKeyConstraint('id_student'),
    schema='u'
    )
    op.create_table('teacher',
    sa.Column('id_teacher', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('code_employee', sa.String(length=45), nullable=True),
    sa.Column('speciality', sa.String(length=45), nullable=True),
    sa.Column('type_contract', sa.String(length=45), nullable=True),
    sa.Column('hiring_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['u.user.id_user'], ),
    sa.PrimaryKeyConstraint('id_teacher'),
    schema='u'
    )
    op.create_table('history_academic',
    sa.Column('id_history', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_estudent', sa.Integer(), nullable=False),
    sa.Column('id_period', sa.Integer(), nullable=False),
    sa.Column('average_semester', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('average_accumulator', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('credits_aproved', sa.String(length=45), nullable=True),
    sa.Column('credits_courses', sa.String(length=45), nullable=True),
    sa.Column('status_academic', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_estudent'], ['u.student.id_student'], ),
    sa.ForeignKeyConstraint(['id_period'], ['u.academic_period.id_period'], ),
    sa.PrimaryKeyConstraint('id_history'),
    schema='u'
    )
    op.create_table('inscription',
    sa.Column('id_inscription', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_student', sa.Integer(), nullable=False),
    sa.Column('id_period', sa.Integer(), nullable=False),
    sa.Column('inscription_date', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('inscription_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('inscription_type', sa.String(length=50), nullable=True),
    sa.Column('enrolled_credits', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_period'], ['u.academic_period.id_period'], ),
    sa.ForeignKeyConstraint(['id_student'], ['u.student.id_student'], ),
    sa.PrimaryKeyConstraint('id_inscription'),
    schema='u'
    )
    op.create_table('subject',
    sa.Column('id_subject', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_program', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('theoretical_hours', sa.Integer(), nullable=False),
    sa.Column('practical_hours', sa.Integer(), nullable=False),
    sa.Column('suggested_semester', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_program'], ['u.program.id_program'], ),
    sa.PrimaryKeyConstraint('id_subject'),
    schema='u'
    )
    op.create_table('group',
    sa.Column('id_group', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_subject', sa.Integer(), nullable=False),
    sa.Column('id_teacher', sa.Integer(), nullable=False),
    sa.Column('id_period', sa.Integer(), nullable=True),
    sa.Column('code_group', sa.String(length=45), nullable=True),
    sa.Column('maximum_quota', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_period'], ['u.academic_period.id_period'], ),
    sa.ForeignKeyConstraint(['id_subject'], ['u.subject.id_subject'], ),
    sa.ForeignKeyConstraint(['id_teacher'], ['u.teacher.id_teacher'], ),
    sa.PrimaryKeyConstraint('id_group'),
    schema='u'
    )
    op.create_table('prerequisite',
    sa.Column('id_prerequisite', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_subject', sa.Integer(), nullable=False),
    sa.Column('Prerequisite_type', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['id_subject'], ['u.subject.id_subject'], ),
    sa.PrimaryKeyConstraint('id_prerequisite'),
    schema='u'
    )
    op.create_table('subject_inscription',
    sa.Column('id_subject_inscription', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_inscription', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['u.group.id_group'], ),
    sa.ForeignKeyConstraint(['id_inscription'], ['u.inscription.id_inscription'], ),
    sa.PrimaryKeyConstraint('id_subject_inscription'),
    schema='u'
    )
    op.create_table('timetable',
    sa.Column('id_timetable', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=45), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('classroom', sa.String(length=45), nullable=True),
    sa.Column('building', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['u.group.id_group'], ),
    sa.PrimaryKeyConstraint('id_timetable'),
    schema='u'
    )
    op.create_table('definitive',
    sa.Column('id_definitive', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_subject_inscription', sa.Integer(), nullable=False),
    sa.Column('final_note', sa.DECIMAL(), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['id_subject_inscription'], ['u.subject_inscription.id_subject_inscription'], ),
    sa.PrimaryKeyConstraint('id_definitive'),
    schema='u'
    )
    op.create_table('grade',
    sa.Column('id_grade', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_subject_inscription', sa.Integer(), nullable=False),
    sa.Column('evaluation_type', sa.String(length=45), nullable=True),
    sa.Column('grade_value', sa.DECIMAL(), nullable=True),
    sa.Column('percentage', sa.DECIMAL(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('observations', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_subject_inscription'], ['u.subject_inscription.id_subject_inscription'], ),
    sa.PrimaryKeyConstraint('id_grade'),
    schema='u'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade', schema='u')
    op.drop_table('definitive', schema='u')
    op.drop_table('timetable', schema='u')
    op.drop_table('subject_inscription', schema='u')
    op.drop_table('prerequisite', schema='u')
    op.drop_table('group', schema='u')
    op.drop_table('subject', schema='u')
    op.drop_table('inscription', schema='u')
    op.drop_table('history_academic', schema='u')
    op.drop_table('teacher', schema='u')
    op.drop_table('student', schema='u')
    op.drop_table('program', schema='u')
    op.drop_table('user', schema='u')
    op.drop_table('faculty', schema='u')
    op.drop_table('academic_period', schema='u')
    # ### end Alembic commands ###
